# Generated by Django 5.1.4 on 2025-01-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0002_remove_product_discount_discount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(default='947c387a-3336-4cf2-a30e-d5ba6414342e', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='eCommerceApp.product'),
            preserve_default=False,
        ),
    ]
